before_script:
  - "git clean -fdxq"
  - "git submodule sync --recursive"
  - "git submodule foreach --recursive git reset --hard"
  - "git submodule update --init --recursive"

Test Deployment: 
  tags:
    - windows
    - dotnet
    - nuget

  except:
    - master

  script:
    - "cd .\\src"
    - "nuget restore SDL.csproj"
    - "powershell.exe -file \".\\ReplaceVersion.ps1\""
#    - "powershell.exe -file \".\\SignBuild.ps1\" 1" -- Requires --no-build
    - "dotnet pack -c Debug -o .\\"

Production Deployment: 
  tags:
    - windows
    - dotnet
    - nuget

  only:
    - master

  script:
    - "cd .\\src"
    - "nuget restore SDL.csproj"
    - "powershell.exe -file \".\\ReplaceVersion.ps1\""
    - "\"C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\MSBuild\\15.0\\Bin\\msbuild.exe\" SDL.csproj /p:Configuration=\"Release\" /p:BuildProjectReferences=true"
#    - "powershell.exe -file \".\\SignBuild.ps1\" 0"
    - "dotnet pack -c Release -o .\\"
    - "dotnet nuget push *.nupkg -k %NUGET_API_KEY% -s \"https://www.nuget.org\""
