before_script:
  - "git clean -fdxq"
  - "git submodule sync --recursive"
  - "git submodule foreach --recursive git reset --hard"
  - "git submodule update --init --recursive"

Test Deployment: 
  tags:
    - windows
    - dotnet

  except:
    - master

  script:
    - "cd .\\src"
    - "dotnet restore SDL.csproj"
    - "powershell.exe -file \"..\\ReplaceVersion.ps1\""
#    - "powershell.exe -file \"..\\SignBuild.ps1\" 1" -- Requires --no-build
    - "dotnet pack -c Debug -o .\\"

Production Deployment: 
  tags:
    - windows
    - dotnet

  only:
    - master

  script:
    - "cd .\\src"
    - "dotnet restore SDL.csproj"
    - "powershell.exe -file \"..\\ReplaceVersion.ps1\""
#    - "powershell.exe -file \"..\\SignBuild.ps1\" 0"
    - "dotnet pack -c Release -o .\\"
    - "dotnet nuget push *.nupkg -k %NUGET_API_KEY% -s \"https://www.nuget.org\""
